/* Lógico_2aaa: */

CREATE TABLE LIVRO (
    CodigoDoLivro INTEGER PRIMARY KEY,
    Titulo VARCHAR,
    FK_CATEGORIA_CodigoCategoria INTEGER,
    FK_EDITORA_CodigoDaEditora INTEGER
);

CREATE TABLE CATEGORIA (
    CodigoCategoria INTEGER PRIMARY KEY,
    Categoria VARCHAR
);

CREATE TABLE AUTOR (
    CodigoDoAutor INTEGER PRIMARY KEY,
    NomeDoAutor VARCHAR
);

CREATE TABLE EDITORA (
    CodigoDaEditora INTEGER PRIMARY KEY,
    NomeDaEditora VARCHAR
);

CREATE TABLE USUARIO (
    CodigoDoUsuario INTEGER PRIMARY KEY,
    NomeDoUsuario VARCHAR,
    TelefoneDoUsuario VARCHAR
);

CREATE TABLE EMPRESTIMO (
    CodigoDoEmprestimo INTEGER PRIMARY KEY,
    DataDoEmprestimo DATE,
    DataDaDevolucao DATE,
    FK_LIVRO_CodigoDoLivro INTEGER,
    FK_USUARIO_CodigoDoUsuario INTEGER
);

CREATE TABLE PERTENCE (
    FK_LIVRO_CodigoDoLivro INTEGER,
    FK_AUTOR_CodigoDoAutor INTEGER
);
 
ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_2
    FOREIGN KEY (FK_CATEGORIA_CodigoCategoria)
    REFERENCES CATEGORIA (CodigoCategoria)
    ON DELETE RESTRICT;
 
ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_3
    FOREIGN KEY (FK_EDITORA_CodigoDaEditora)
    REFERENCES EDITORA (CodigoDaEditora)
    ON DELETE RESTRICT;
 
ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_2
    FOREIGN KEY (FK_LIVRO_CodigoDoLivro)
    REFERENCES LIVRO (CodigoDoLivro)
    ON DELETE RESTRICT;
 
ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_3
    FOREIGN KEY (FK_USUARIO_CodigoDoUsuario)
    REFERENCES USUARIO (CodigoDoUsuario)
    ON DELETE CASCADE;
 
ALTER TABLE PERTENCE ADD CONSTRAINT FK_PERTENCE_1
    FOREIGN KEY (FK_LIVRO_CodigoDoLivro)
    REFERENCES LIVRO (CodigoDoLivro)
    ON DELETE RESTRICT;
 
ALTER TABLE PERTENCE ADD CONSTRAINT FK_PERTENCE_2
    FOREIGN KEY (FK_AUTOR_CodigoDoAutor)
    REFERENCES AUTOR (CodigoDoAutor)
    ON DELETE RESTRICT;